name: Build & Site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # Manual trigger.

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  ci:
    name: CI / Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build & Verify
        run: mvn -B clean verify

      - name: Upload Report Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maven-reports
          path: |
            target/surefire-reports/*.xml
            target/failsafe-reports/*.xml
            target/pmd.xml

  site:
    name: Generate & Deploy Site
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'  # Master branch only.
    needs: ci # It requires artifacts from the "ci" job to be downloaded and used for site report.
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Download Reports from CI
        uses: actions/download-artifact@v4
        with:
          name: maven-reports
          path: target/ # Downloads the files back into the target directory.

      - name: Generate Site
        # -DskipTests prevents re-running tests.
        # The site plugin will now find the XMLs in target/ and generate HTML from them.
        run: mvn site -DskipTests

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
